# -*- coding: utf-8 -*-
"""user_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GaiooZt0joyLDx10YdJjkf48tuxL3gYh
"""

import csv
import hashlib
import random
import string

def generate_random_string(length=8):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

def generate_user_data(num_users=100):
    users = []
    email = []
    name = [
    'Liam', 'Olivia', 'Noah', 'Emma', 'Oliver', 'Ava', 'Elijah', 'Charlotte', 'William', 'Sophia',
    'James', 'Amelia', 'Benjamin', 'Isabella', 'Lucas', 'Mia', 'Henry', 'Evelyn', 'Alexander', 'Harper',
    'Michael', 'Camila', 'Ethan', 'Abigail', 'Daniel', 'Emily', 'Matthew', 'Elizabeth', 'Jackson', 'Mila',
    'Sebastian', 'Ella', 'Aiden', 'Avery', 'David', 'Sofia', 'Joseph', 'Aria', 'Carter', 'Scarlett',
    'Owen', 'Victoria', 'Wyatt', 'Madison', 'John', 'Luna', 'Jack', 'Grace', 'Luke', 'Chloe',
    'Jayden', 'Penelope', 'Dylan', 'Layla', 'Grayson', 'Riley', 'Levi', 'Zoey', 'Isaac', 'Nora',
    'Gabriel', 'Lily', 'Julian', 'Hannah', 'Mateo', 'Aubrey', 'Anthony', 'Lillian', 'Jaxon', 'Addison',
    'Lincoln', 'Elena', 'Joshua', 'Stella', 'Christopher', 'Natalie', 'Andrew', 'Zoe', 'Theodore', 'Leah',
    'Caleb', 'Hazel', 'Ryan', 'Violet', 'Asher', 'Aurora', 'Nathan', 'Savannah', 'Thomas', 'Audrey',
    'Leo', 'Brooklyn', 'Isaiah', 'Bella', 'Charles', 'Claire', 'Josiah', 'Lucy', 'Hudson', 'Paisley'
    ]
    for i in name:
      a = i.lower()+"@example.com"
      if a in email:
        email.append(i.lower()+generate_random_string(3)+"@example.com")
        e = i.lower()+generate_random_string(3)+"@example.com"
      else:
        email.append(a)
        e = a
      password = generate_random_string(random.randint(8, 12))
      hashed_password = hashlib.sha256(password.encode()).hexdigest()
      users.append((i, e, password, hashed_password))
    return users

def save_to_csv(data, filename='user_data.csv'):
    with open(filename, 'w', newline='') as csvfile:
        csv_writer = csv.writer(csvfile)
        csv_writer.writerow(['Name', 'Email','password', 'hashed_password'])
        csv_writer.writerows(data)

if __name__ == "__main__":
    user_data = generate_user_data()
    save_to_csv(user_data)
    print("User data has been generated and saved to user_data.csv")